import React from 'react'

export function About() {
    return (
        <div className="about-container">
            Arik Alex and Alisa are the best damn programmers this side of the Atlantic.
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit qui aliquam impedit reiciendis nobis consequatur sapiente quod itaque eius temporibus mollitia quos vero quisquam animi aspernatur tenetur, rem consequuntur ea possimus ut fuga, laboriosam ipsam reprehenderit quam! Reiciendis, rerum est. Aliquid cupiditate sequi iusto ducimus perferendis molestias voluptates deleniti ad numquam est corporis suscipit maxime obcaecati reprehenderit doloribus quia et distinctio officiis, omnis incidunt aspernatur! At, aspernatur iste odit adipisci numquam eaque temporibus non, quidem assumenda a aperiam exercitationem, quod accusamus laborum saepe ea cupiditate suscipit sed distinctio! Voluptate voluptatem molestias dolorem impedit inventore maxime non neque asperiores possimus cupiditate.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eius voluptatum doloribus delectus quia velit corrupti modi voluptatibus ducimus voluptates adipisci sequi, excepturi quos neque quae soluta sunt tempora fugiat quas, aliquam aut alias ea, odit veniam officiis! Autem placeat maiores, consequuntur ducimus aspernatur quae, nostrum culpa quidem odit vero minus. Veritatis, impedit labore blanditiis accusamus optio atque minus cumque? Porro perferendis animi vitae, molestiae adipisci ea repellat error harum quos eveniet velit ipsa cum sapiente corporis hic debitis minima. Iste autem harum rerum natus saepe illo culpa consequatur molestias voluptatibus architecto, et quidem voluptatem blanditiis, animi nihil placeat tempore commodi similique, voluptates velit est assumenda! Saepe quod commodi doloremque illo, explicabo nisi molestiae dolorum sed impedit consectetur iure aliquam incidunt eos odit et, magnam at aut unde vitae velit! Dolores expedita, voluptatum molestiae cupiditate fuga vero quod provident odit, doloribus, architecto eaque explicabo temporibus magni eum blanditiis libero dignissimos voluptates atque autem delectus ab minus eligendi! Rem nostrum non saepe velit expedita natus ex ea hic dolore, aperiam, itaque optio ipsam tempora ut facere error laudantium minima. Cumque officia velit, laudantium magni perspiciatis repellendus vel tempore perferendis repudiandae et, doloremque quis eaque atque delectus est odio quia aperiam beatae magnam, voluptatibus rerum praesentium reiciendis quasi amet. Aut voluptatibus aliquid nostrum tenetur laborum magni libero delectus tempore excepturi exercitationem suscipit ipsa, vel consequuntur ducimus accusantium quas! Omnis minima recusandae molestiae mollitia at illum laborum esse dolore deserunt dolorum impedit, ipsa suscipit nesciunt saepe! Odio, ut numquam ipsa aliquid neque error id ducimus? Illum, itaque nemo inventore voluptas nihil accusantium assumenda debitis! Accusamus facilis repellat officia maxime necessitatibus nemo obcaecati enim, provident reiciendis modi eius consectetur perspiciatis omnis praesentium rem, quisquam officiis. Tempore veritatis, excepturi laborum cumque inventore optio nesciunt corrupti? Doloremque, nisi! A fugit numquam consequuntur distinctio laudantium ipsum repellendus ullam.
        </div>
    )
}
